### ISSUE TITLE
是否能同步放置於curseforge

### ISSUE THREAD

**Issue by Shuuen-Yukibi** [YTGLD/MoonsTeams#1]
QQ對我來說非常不友好

而且我想在curseforge組建模組包

**Comment by YTGLD** [comment]
放心，我会尽可能的想办法传上去。

**Comment by YTGLD** [comment]
https://www.curseforge.com/minecraft/mc-mods/moonstone

**Comment by Shuuen-Yukibi** [comment]
謝謝作者大大
