### ISSUE TITLE
Vivecraft 1.21.1 NeoForge

### ISSUE THREAD

**Issue by ElenaNya** [YTGLD/MoonsTeams#5]
moonstone 1.1.4.3-neoforge
Vivecraft 1.21.1-1.1.14-b2-neoforge

Hello! When using Vicecraft with your mod, Vivecraft starts behaving oddly, the window shrinks, and everything begins to render strangely.

![image](https://github.com/user-attachments/assets/64e10d32-9aac-4c44-bf58-ceabf60dcd51)
![image](https://github.com/user-attachments/assets/33267d5d-c735-48da-b347-adaa7eed26a7)

**Comment by YTGLD** [comment]
这看起来是PoseStack的渲染出了问题，请问在这件事情发生之前您做了什么。或者说只是装了这个模组就有问题吗？

This seems to be a rendering issue with PoseStack. What did you do before this happened.
Or is it just installing this module that there is a problem？

Sorry, my English is not good

**Comment by ElenaNya** [comment]
If I understand correctly, just having these mods (Moonstone, Vivecraft) together in the mods folder causes this strange behavior

**Comment by YTGLD** [comment]
> 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为

根据我参阅的资料(https://www.mcmod.cn/class/1119.html)我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。
﻿
我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题
﻿
最后。请问在事发时，你的日志中有什么异常吗？
﻿
﻿

**Comment by ElenaNya** [comment]
seems like there was nothing unusual in the logs. We tried checking them, but there didn’t seem to be anything about Moonstone there. I didn’t know Vivecraft uses something from Optifine. Maybe it’s worth letting them know about this issue too?

If you give us a little time, we’ll try to gather some information from the logs using only Vivecraft and Moonstone in the near future. The logs I sharing with you right now are quite old, from when we were first looking for incompatibilities between mods in modpack.

Also, I’d like to apologize, as this seems to be something that might be difficult to resolve. However, we’ll do our best to provide as much information as possible. Apologies for adding troubles to you 🙇

[latest.log](https://github.com/user-attachments/files/18045888/latest.log)

**Comment by chmonyasik** [comment]
> > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> 
> 根据我参阅的资料 (https://www.mcmod.cn/class/1119.html) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。 ﻿ 我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 ﻿ 最后。请问在事发时，你的日志中有什么异常吗？

![Screenshot_4](https://github.com/user-attachments/assets/d1daf3a9-624c-496b-804a-71b6fd6c78bf)

[latest.log](https://github.com/user-attachments/files/18127906/latest.log)

**Comment by YTGLD** [comment]
> > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > 
> > 
> > 根据我参阅的资料 （https://www.mcmod.cn/class/1119.html） 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> 
> ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> 
> [latest.log](https://github.com/user-attachments/files/18127906/latest.log)

I seem to have found the problem. Although I don't have a VR device to test, I feel like there's no problem anymore. I hope you can go and test it

at：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge

**Comment by chmonyasik** [comment]
> > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > 
> > > 
> > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > 
> > 
> > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> 
> I seem to have found the problem. Although I don't have a VR device to test, I feel like there's no problem anymore. I hope you can go and test it
> 
> at：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge

Hi! Thank you, but unfortunately nothing has changed 😕

[latest.log](https://github.com/user-attachments/files/18149966/latest.log)

**Comment by YTGLD** [comment]
> > > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > > 
> > > > 
> > > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > > 
> > > 
> > > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> > 
> > 
> > 我似乎发现了问题所在。虽然我没有要测试的 VR 设备，但我觉得已经没有问题了。我希望你能去测试一下
> > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge
> 
> 你好！谢谢你，但不幸的是，一切都没有改变 😕
> 
> [latest.log](https://github.com/user-attachments/files/18149966/latest.log)


I seem to have found the problem, which is caused by an error due to a mismatch in the size of the RenderTarget,
（MainTarget size: 2316x2476, RenderTarget size: 1280x720. ）

But I'm not sure if I can really deal with this problem,
Please give me some chance, I will try my best to fix it

at：https://modrinth.com/mod/moonstone/version/1.1.5.3-neoforge

**Comment by chmonyasik** [comment]
> > > > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > > > 
> > > > > 
> > > > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > > > 
> > > > 
> > > > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > > > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> > > 
> > > 
> > > 我似乎发现了问题所在。虽然我没有要测试的 VR 设备，但我觉得已经没有问题了。我希望你能去测试一下
> > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge
> > 
> > 
> > 你好！谢谢你，但不幸的是，一切都没有改变 😕
> > [latest.log](https://github.com/user-attachments/files/18149966/latest.log)
> 
> I seem to have found the problem, which is caused by an error due to a mismatch in the size of the RenderTarget, （MainTarget size: 2316x2476, RenderTarget size: 1280x720. ）
> 
> But I'm not sure if I can really deal with this problem, Please give me some chance, I will try my best to fix it
> 
> at：https://modrinth.com/mod/moonstone/version/1.1.5.3-neoforge

Thank you again! But unfortunately, nothing has changed once more. (For convenience, you can send the mod here for testing if it’s easier for you instead of uploading it to Modrinth) If it becomes too difficult for you, maybe it’s worth asking for help in the Vivecraft Discord?
[latest (1).log](https://github.com/user-attachments/files/18150837/latest.1.log)

**Comment by YTGLD** [comment]
> > > > > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > > > > 
> > > > > > 
> > > > > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > > > > 
> > > > > 
> > > > > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > > > > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> > > > 
> > > > 
> > > > 我似乎发现了问题所在。虽然我没有要测试的 VR 设备，但我觉得已经没有问题了。我希望你能去测试一下
> > > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge
> > > 
> > > 
> > > 你好！谢谢你，但不幸的是，一切都没有改变 😕 [latest.log](https://github.com/user-attachments/files/18149966/latest.log)
> > 
> > 
> > 我似乎发现了问题，这是由 RenderTarget 大小不匹配引起的错误引起的，（MainTarget 大小：2316x2476，RenderTarget 大小：1280x720。）
> > 但是我不确定我是否真的能处理这个问题，请给我一些机会，我会尽力解决它
> > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.3-neoforge
> 
> 再次感谢！但不幸的是，一切都没有再次改变。（为方便起见，您可以将 Mod 发送到此处进行测试，而不是将其上传到 Modrinth）如果这对您来说太难了，也许值得在 Vivecraft Discord 中寻求帮助？ [最新 （1）.log](https://github.com/user-attachments/files/18150837/latest.1.log)

I have asked many people I can meet, but none of them have had much effect, so I am powerless to help with this question.

**Comment by chmonyasik** [comment]
> > > > > > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > > > > > 
> > > > > > > 
> > > > > > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > > > > > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> > > > > 
> > > > > 
> > > > > 我似乎发现了问题所在。虽然我没有要测试的 VR 设备，但我觉得已经没有问题了。我希望你能去测试一下
> > > > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge
> > > > 
> > > > 
> > > > 你好！谢谢你，但不幸的是，一切都没有改变 😕 [latest.log](https://github.com/user-attachments/files/18149966/latest.log)
> > > 
> > > 
> > > 我似乎发现了问题，这是由 RenderTarget 大小不匹配引起的错误引起的，（MainTarget 大小：2316x2476，RenderTarget 大小：1280x720。）
> > > 但是我不确定我是否真的能处理这个问题，请给我一些机会，我会尽力解决它
> > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.3-neoforge
> > 
> > 
> > 再次感谢！但不幸的是，一切都没有再次改变。（为方便起见，您可以将 Mod 发送到此处进行测试，而不是将其上传到 Modrinth）如果这对您来说太难了，也许值得在 Vivecraft Discord 中寻求帮助？ [最新 （1）.log](https://github.com/user-attachments/files/18150837/latest.1.log)
> 
> I have asked many people I can meet, but none of them have had much effect, so I am powerless to help with this question.

Anyway, thank you for your help! I asked for assistance in the Vivecraft Discord, and if I understood correctly, the issue is now on Vivecraft's side

**Comment by chmonyasik** [comment]
> > > > > > > > 如果我理解正确，只要将这些 mod（Moonstone、Vivecraft）放在 mods 文件夹中就会导致这种奇怪的行为
> > > > > > > 
> > > > > > > 
> > > > > > > 根据我参阅的资料 （[https://www.mcmod.cn/class/1119.html）](https://www.mcmod.cn/class/1119.html%EF%BC%89) 我发现Vivecraft时内置OptiFine 的，我并不确定Moonstone是否兼容类似的渲染模组。我无法进行测试，因为我没有相应的VR设备，但我会尽可能的帮你解决这个问题 最后。请问在事发时，你的日志中有什么异常吗？
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_4](https://private-user-images.githubusercontent.com/94359925/395603866-d1daf3a9-624c-496b-804a-71b6fd6c78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzA1NzgsIm5iZiI6MTczNDMzMDI3OCwicGF0aCI6Ii85NDM1OTkyNS8zOTU2MDM4NjYtZDFkYWYzYTktNjI0Yy00OTZiLTgwNGEtNzFiNmZkNmM3OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzVmYjBjOWU3NTM1NWM2MTIxMDYzZDU3YTU4NjA4MTVhZWU1Y2VmNjkwM2JhZmRiNzI2MWQ3ZjVjYTM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mJ1WoD9AglO9jhNhsJ4lL3jk1bL5OPavU65D_dov-Q)
> > > > > > [latest.log](https://github.com/user-attachments/files/18127906/latest.log)
> > > > > 
> > > > > 
> > > > > 我似乎发现了问题所在。虽然我没有要测试的 VR 设备，但我觉得已经没有问题了。我希望你能去测试一下
> > > > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.2-neoforge
> > > > 
> > > > 
> > > > 你好！谢谢你，但不幸的是，一切都没有改变 😕 [latest.log](https://github.com/user-attachments/files/18149966/latest.log)
> > > 
> > > 
> > > 我似乎发现了问题，这是由 RenderTarget 大小不匹配引起的错误引起的，（MainTarget 大小：2316x2476，RenderTarget 大小：1280x720。）
> > > 但是我不确定我是否真的能处理这个问题，请给我一些机会，我会尽力解决它
> > > 地点：https://modrinth.com/mod/moonstone/version/1.1.5.3-neoforge
> > 
> > 
> > 再次感谢！但不幸的是，一切都没有再次改变。（为方便起见，您可以将 Mod 发送到此处进行测试，而不是将其上传到 Modrinth）如果这对您来说太难了，也许值得在 Vivecraft Discord 中寻求帮助？ [最新 （1）.log](https://github.com/user-attachments/files/18150837/latest.1.log)
> 
> I have asked many people I can meet, but none of them have had much effect, so I am powerless to help with this question.

The new version of Vivecraft fixes the issue, thank you so much for your help!
